namespace NSass.Script
{
    public enum TokenType
    {
        SymLit,
        Plus,
        Minus,
        Times,
        Div,
        Mod,
        SingleEq,
        Colon,
        LParen,
        RParen,
        Comma,
        Ampersand,
        And,
        Or,
        Not,
        Eq,
        Neq,
        Gte,
        Lte,
        Gt,
        Lt,
        BeginInterpolation,
        EndInterpolation,
        SemiColon,
        LCurly,
        Splat
    }
}
