namespace NSass.Script
{
    public enum TokenType
    {
        WhiteSpace,
        SymLit,
        Variable,
        Comment,
        ////BeginInterpolation,
        EndInterpolation,
        SemiColon,
        LCurly,
        Colon,
        Comma,
        Ampersand,
        Plus,
        Minus,
        Times,
        Div,
        ////Mod,
        ////SingleEq,
        LParen,
        RParen
        ////And,
        ////Or,
        ////Not,
        ////Eq,
        ////Neq,
        ////Gte,
        ////Lte,
        ////Gt,
        ////Lt,
        ////Splat
    }
}
